[project]
name = "prakt"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "openpyxl>=3.1.5",
    "psycopg[binary]>=3.2.9",
    "transliterate>=1.10.2",
]
